---
- hosts: localhost

  tasks:
  - name: check for existence of ~/.ansible/cert-manager-secrets.yml
    ansible.builtin.stat:
      path: ~/.ansible/cert-manager-secrets.yml
    register: secrets_file

  - name: check for existence of ~/.ansible/vaultpassword
    ansible.builtin.stat:
      path: ~/.ansible/vaultpassword
    register: password_file

  - name: create secret file
    block:  
    - name: Pausing for root_passphrase
      ansible.builtin.pause:
        prompt: CA root passphrase
      register: root_passphrase_prompt
      no_log: true
    - ansible.builtin.set_fact:
        root_passphrase: "{{ root_passphrase_prompt.user_input }}"
    - name: display CA root passphrase
      ansible.builtin.debug:
        msg: "root_passphrase: {{ root_passphrase }}"
  
    - name: Pausing for intermediate_passphrase
      ansible.builtin.pause:
        prompt: Intermediate certificate  passphrase
      register: intermediate_passphrase_prompt
      no_log: true
    - ansible.builtin.set_fact:
        intermediate_passphrase: "{{ intermediate_passphrase_prompt.user_input }}"
    - name: display CA root passphrase
      ansible.builtin.debug:
        msg: "intermediate_passphrase: {{ intermediate_passphrase }}"

    - name: create cert-manager-secrets.yml variable file in ~/.ansible on control node
      ansible.builtin.template:
        src: cert-manager-secrets.yml.j2
        dest: ~/.ansible/cert-manager-secrets.yml
        mode: '0600'
    when: not secrets_file.stat.exists

  - name: create default ansible vault password file (~/.ansible/vaultpassword) with correct permissons
    ansible.builtin.copy:
      dest: ~/.ansible/vaultpassword
      mode: '0600'
      content: |
        ***IMPORTANT***: Replace the contents of this line (no newline) with your ansible vault password in plaintext
    when: not password_file.stat.exists
