#
# (c) Copyright 2020 Jeff Kight
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Ansible playbooks to Manage CAs, Intermediate CAs and Certificates
#
# Author: Jeff Kight <jeff@kight.net>
#
---

- hosts: localhost
  connection: local
  gather_facts: yes

  roles:
    - cert-manager

  tasks:
    - set_fact:
        tls_dir: "{{ tls_root }}/{{ cert_domain }}"

    - set_fact:
        cert_servers_ips: "{{ cert_servers | union(cert_ips) }}"
        host_dir: "{{ tls_dir }}/{{ store_dir }}/{{ cert_servers[0] }}/{{ ansible_date_time.date }}"

    - import_tasks: roles/cert-manager/tasks/prep_certs.yml
    - import_tasks: roles/cert-manager/tasks/create_cert.yml
