#
# (c) Copyright 2019 Jeff Kight
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Ansible playbooks for CAs, CSRs and Certs
#
# Author: Jeff Kight <jeff@kight.net>
#
---

- name: Create private key and CSR for the server
  shell: >
    {{ openssl_cmd }} req
    -config {{ host_config }}
    -newkey rsa:2048
    -nodes
    -keyout {{ cert_servers[0] }}.{{ host_key_suffix }}
    -out {{ cert_servers[0] }}.{{ host_csr_suffix }}
    -subj "/C={{ cert_country }}/ST={{ cert_state }}/O={{ cert_org }}/OU={{ cert_org_unit }}/CN={{ cert_servers[0] }}"
    -days {{ cert_duration }}
  args:
    chdir: "{{ host_dir }}"
    creates: "{{ cert_servers[0] }}.{{ host_csr_suffix }}"

- name: Create the server certificate
  shell: >
    {{ openssl_cmd }} ca
    -config {{ ca_config }}
    -extensions server_cert
    -days {{ cert_duration }}
    -notext
    -md sha512
    -in ../../../{{ host_dir}}/{{ cert_servers[0] }}.{{ host_csr_suffix }}
    -out ../../../{{ host_dir}}/{{ cert_servers[0] }}.{{ host_cert_suffix }}
    -passin 'pass:{{ intermediate_passphrase }}'
    -batch
  args:
    chdir: "{{ tls_dir }}/{{ int_ca_dir }}"
    creates: "../../../{{ host_dir}}/{{ cert_servers[0] }}.{{ host_cert_suffix }}"
  when:
    - cert_server | bool
    - not cert_client | bool

- name: Create the client certificate
  shell: >
    {{ openssl_cmd }} ca
    -config {{ ca_config }}
    -extensions usr_cert
    -days {{ cert_duration }}
    -notext
    -md sha512
    -in ../../../{{ host_dir}}/{{ cert_servers[0] }}.{{ host_csr_suffix }}
    -out ../../../{{ host_dir}}/{{ cert_servers[0] }}.{{ host_cert_suffix }}
    -passin 'pass:{{ intermediate_passphrase }}'
    -batch
  args:
    chdir: "{{ tls_dir }}/{{ int_ca_dir }}"
    creates: "../../../{{ host_dir}}/{{ cert_servers[0] }}.{{ host_cert_suffix }}"
  when:
    - not cert_server | bool
    - cert_client | bool

- name: Create the server+client certificate
  shell: >
    {{ openssl_cmd }} ca
    -config {{ ca_config }}
    -extensions server_usr_cert
    -days {{ cert_duration }}
    -notext
    -md sha512
    -in ../../../{{ host_dir}}/{{ cert_servers[0] }}.{{ host_csr_suffix }}
    -out ../../../{{ host_dir}}/{{ cert_servers[0] }}.{{ host_cert_suffix }}
    -passin 'pass:{{ intermediate_passphrase }}'
    -batch
  args:
    chdir: "{{ tls_dir }}/{{ int_ca_dir }}"
    creates: "../../../{{ host_dir}}/{{ cert_servers[0] }}.{{ host_cert_suffix }}"
  when:
    - cert_server | bool
    - cert_client | bool

- name: Create combined certificate
  shell: >
    cat
    {{ cert_servers[0] }}.{{ host_key_suffix }}
    {{ cert_servers[0] }}.{{ host_cert_suffix }}
    > {{ cert_servers[0] }}.{{ host_key_cert_suffix }}
  args:
    chdir: "{{ host_dir }}"
    creates: "{{ cert_servers[0] }}.{{ host_key_cert_suffix }}"

- name: Create compressed archive of key and certificate files
  community.general.archive:
    path:
    - "{{ host_dir }}/*.{{ host_cert_suffix }}"
    - "{{ host_dir }}/*.{{ host_key_suffix }}"
    - "{{ host_dir }}/*.{{ host_key_cert_suffix }}"
    dest: "{{ host_dir }}/{{ cert_servers[0] }}.gz"
    format: gz
